### ISSUE TITLE
minikube start failed: Unit file cri-docker.socket does not exist.

### ISSUE THREAD

**Issue by gogobody** [Mirantis/cri-dockerd#114]
minikube start failed on my centos7.
```
# minikube start
* minikube v1.26.1 on Centos 7.9.2009
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Updating the running docker "minikube" container ...

X Exiting due to RT_DOCKER_MISSING_CRI_DOCKER_NONE: sudo systemctl enable cri-docker.socket: Process exited with status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

* Suggestion: Using Kubernetes v1.24+ with the Docker runtime requires cri-docker to be installed
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none
* Related issue: https://github.com/kubernetes/minikube/issues/14410
```
```
sudo systemctl list-unit-files | grep cri-docker
cri-docker.service                            disabled
cri-docker.socket                             enabled
```

**Comment by neersighted** [comment]
This looks like a local configuration/environment, or a minikube issue -- from what you've posted `cri-dockerd` is installed and the unit file is enabled. There is not much more to do on the cri-dockerd end other than enabling the unit file.

**Comment by gogobody** [comment]
> This looks like a local configuration/environment, or a minikube issue -- from what you've posted `cri-dockerd` is installed and the unit file is enabled. There is not much more to do on the cri-dockerd end other than enabling the unit file.

I installed latest el7.x86-64 rpm package on my centos7, and then executed:
```
systemctl daemon-reload
systemctl enable cri-docker.service
systemctl enable --now cri-docker.socket
```

```
$ ls /usr/lib/systemd/system/cri-docker.s
cri-docker.service  cri-docker.socket
```

**Comment by neersighted** [comment]
Check `systemctl status cri-dockerd.service` -- if the daemon is running, everything is correct from the cri-dockerd end.

**Comment by gogobody** [comment]
Yes, it's correct. Thank you, I will go to minikube to find a solution.
