### ISSUE TITLE
go build -o bin/cri-dockerd error 

### ISSUE THREAD

**Issue by xyzstar** [Mirantis/cri-dockerd#118]
ubuntu 22 
#apt  install golang-go
#go version
go version go1.18.1 linux/amd64
# go build -o bin/cri-dockerd
cmd/server.go:31:2: cannot find package "." in:
        /root/cri-dockerd/vendor/net/netip

**Comment by coreylam** [comment]
i got the same error since there is a lower version go(1.17.12), and use installer_linux install go(1.20 in /root/.go), try to uninstall the go(1.17.12), and it works.
