### ISSUE TITLE
v0.3.0 release assets not packaged to .tgz files (as on v0.2.6 and prior)

### ISSUE THREAD

**Issue by consideRatio** [Mirantis/cri-dockerd#140]
While this could be acceptable, its unexpected and would merit a note in the changelog / release notes if intended.

For comparison, see:

- https://github.com/Mirantis/cri-dockerd/releases/tag/v0.3.0 (different)

  [cri-dockerd-0.3.0.amd64](https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.0/cri-dockerd-0.3.0.amd64) 52.1 MB yesterday
  [cri-dockerd-0.3.0.arm64](https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.0/cri-dockerd-0.3.0.arm64) 50.4 MB yesterday
  [cri-dockerd-0.3.0.darwin.amd64](https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.0/cri-dockerd-0.3.0.darwin.amd64) 50.3 MB yesterday
  [cri-dockerd-0.3.0.win.amd64](https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.0/cri-dockerd-0.3.0.win.amd64) 51.8 MB yesterday
  
- https://github.com/Mirantis/cri-dockerd/releases/tag/v0.2.6

  [cri-dockerd-0.2.6.amd64.tgz](https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.6/cri-dockerd-0.2.6.amd64.tgz) 22 MB Sep 25
  [cri-dockerd-0.2.6.arm64.tgz](https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.6/cri-dockerd-0.2.6.arm64.tgz) 20.4 MB Sep 25
  [cri-dockerd-0.2.6.darwin.amd64.tgz](https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.6/cri-dockerd-0.2.6.darwin.amd64.tgz) 21.1 MB Sep 25
  [cri-dockerd-0.2.6.win.amd64.zip](https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.6/cri-dockerd-0.2.6.win.amd64.zip) 21.7 MB Sep 25

**Comment by neersighted** [comment]
I do believe the uploaded builds on this repository are bench builds performed by @evol262, as the release-tooling is quite stale/hasn't been used in quite some time. I'm willing to reupload .tar.gz compressed artifacts if you think that would be helpful, though I would like to push back on the phrasing "acceptable" -- prebuilt binaries are provided as a convenience, but are obviously not desirable from a security standpoint. For more than trivial/untrusted use I would certainly suggest building from source instead.

A CI-driven release process using goreleaser is probably best here.

**Comment by consideRatio** [comment]
> I'm willing to reupload .tar.gz compressed artifacts if you think that would be helpful

Absolutely, it would be!

What would be most helpful would be to know if some artificat can be counted on to be reliably uploaded as part of the release process. Then upgrading versions can be as easy as updating the version as compared to checking whats available and making per-version decisions.

I'm installing cri-dockerd for a github action that setups a k3s cluster for testing purposes. Including a build-from-source step isn't reasonable there, so if that is what I need to do I'll do it myself first and stash it away. But then of course, it would look less secure for the consumers of the action (https://github.com/jupyterhub/action-k3s-helm#readme) if they would inspect the source code.

**Comment by neersighted** [comment]
I've uploaded compressed versions of the release artifacts based on the previous directory layout.

Regarding any sort of binary assets you can depend on, I don't think those will exist until we integrate goreleaser/nfpm or some other automated release process. I expect PRs are welcome; this project uses GitHub/GitHub Actions and no other tooling/CI infrastructure, as such third-party contributions to CI should be very easy/accessible.

**Comment by imaxun** [comment]
你好目前是否已经支持k8s 1.26版本

**Comment by consideRatio** [comment]
I opened #143 to represent that @neersighted so that this can be closed as resolved! Thank you for your help!
