### ISSUE TITLE
fail to start cri-docker 

### ISSUE THREAD

**Issue by JiinJie** [Mirantis/cri-dockerd#145]
I configed the cri-docker ,and it shows failed to start.  I search the config file from the internet.  
maybe it has some problems,

here are the environment:
**_environment: ubuntu22.04 server
cri-dockerd package: cri-dockerd-0.3.0.amd64.tgz
kubernetes version: 1.26
docker version : 20.10.22, build 3a2c30b_**

![image](https://user-images.githubusercontent.com/35601624/209790552-24e935e8-3724-46dd-ac0d-e707974a4224.png)

here are the configs:

```
cat <<"EOF" > /usr/lib/systemd/system/cri-docker.service
[Unit]
Description=CRI Interface for Docker Application Container Engine
Documentation=https://docs.mirantis.com
After=network-online.target firewalld.service docker.service
Wants=network-online.target
Requires=cri-docker.socket
[Service]
Type=notify
ExecStart=/usr/bin/cri-dockerd --network-plugin=cni --pod-infra-container-image=registry.aliyuncs.com/google_containers/pause:3.7
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always
StartLimitBurst=3
StartLimitInterval=60s
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
Delegate=yes
KillMode=process
[Install]
WantedBy=multi-user.target
EOF
```

```

cat <<"EOF" > /usr/lib/systemd/system/cri-docker.socket
[Unit]
Description=CRI Docker Socket for the API
PartOf=cri-docker.service
[Socket]
ListenStream=%t/cri-dockerd.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker
[Install]
WantedBy=sockets.target
EOF
```

**Comment by afbjorklund** [comment]
If you install units in a local `/etc/systemd`, it will override the packaged defaults in `/usr/lib/systemd`...

You can use `systemctl cat`, to see the combined result (or just remove /etc/systemd/system/cri-docker.service)

**Comment by JiinJie** [comment]
> If you install units in a local `/etc/systemd`, they will _override_ the packaged defaults in `/usr/lib/systemd`...
> 
> You can use `systemctl cat`, to see the combined result (just remove /etc/systemd/system/cri-docker.service)
> 
> The recommendation is to only use an override, and leave the original files from the package.
> 
> https://www.freedesktop.org/software/systemd/man/systemd.unit.html
> 
> dpkg -i [cri-dockerd_0.3.0.3-0.ubuntu-jammy_amd64.deb](https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.0/cri-dockerd_0.3.0.3-0.ubuntu-jammy_amd64.deb)
> 
> /etc/systemd/system/cri-docker.service.d/override.conf
> 
> ```
> [Service]
> ExecStart=
> ExecStart=/usr/bin/cri-dockerd --container-runtime-endpoint fd:// --pod-infra-container-image=registry.aliyuncs.com/google_containers/pause:3.7
> ```
> 
> This situation will improve, once there is a config file (#102)

yeah,it works.thanks a lot

**Comment by JiinJie** [comment]
@evol262   ha-ha, The answer was right in front of me

**Comment by afbjorklund** [comment]
> The answer was right in front of me

Not sure about that, the [upstream documentation](https://kubernetes.io/docs/setup/production-environment/container-runtimes/) seems to only give _half_ of the real answer ?

> **Docker Engine**
> On each of your nodes, install Docker for your Linux distribution as per [Install Docker Engine](https://docs.docker.com/engine/install/#server).
> Install [cri-dockerd](https://github.com/Mirantis/cri-dockerd), following the instructions in that source code repository.
>
> **Overriding the sandbox (pause) image**
> The `cri-dockerd` adapter accepts a command line argument for specifying which container image to use as the Pod infrastructure container (“pause image”). The command line argument to use is `--pod-infra-container-image`.

Specifically, it doesn't mention anything about packages or systemd - or broken socket detection.
