### ISSUE TITLE
Issue with installing cri-docker: Failed to enable unit: Unit file cri-docker.socket does not exist

### ISSUE THREAD

**Issue by Manojkl** [Mirantis/cri-dockerd#146]
I am trying to install cri-docker on my fedora 37 workstations running on a virtual machine.
I followed the steps given in the repository readme.

git clone https://github.com/Mirantis/cri-dockerd.git
\# Install golang
cd cri-dockerd
mkdir bin
go build -o bin/cri-dockerd
mkdir -p /usr/local/bin
install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
cp -a packaging/systemd/* /etc/systemd/system
sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
systemctl daemon-reload
systemctl enable cri-docker.service
systemctl enable --now cri-docker.socket

Everything worked smoothly until `systemctl daemon-reload`
When I run `systemctl enable cri-docker.service` command I get a error stating `Failed to enable unit: Unit file cri-docker.service does not exist.`
Same for the `systemctl enable --now cri-docker.socket` command giving out error as `Failed to enable unit: Unit file cri-docker.socket does not exist.`
I tried to find a solution online and was not able to find a working solution. https://github.com/kubernetes/minikube/issues/14601
Any help is appreciated.

**Comment by neersighted** [comment]
Given the sequence of commands you have provided, as well as the fact that the files clearly exist (as earlier commands would have failed if they did not), it appears that systemd is merely not picking up your newly installed unit files.

This is odd, as `systemctl daemon-reload` is just defensive, and systemd should discover the newly installed units even without that step. Can you confirm that `/etc/systemd/system/cri-docker.{service,socket}` exist?

**Comment by afbjorklund** [comment]
I don't think `cp -a` works here, since systemd requires all units to be owned by root ?

**Comment by neersighted** [comment]
That was my [understanding before](https://github.com/Mirantis/cri-dockerd/issues/122#issuecomment-1273543976), but @evol262 thinks differently. I didn't test it for myself then, as the user solved it by using the packages. In any case, I think the `-a` ought to be omitted as we really should install those files as root, even if it's not the cause of the problem here.

@Manojkl after you confirm those unit files exist, can you `chown root:root /etc/systemd/system/cri-docker.{service,socket}` and try enabling the service and socket again?

**Comment by afbjorklund** [comment]
Also I think it should be using `/usr/local/lib/systemd/system`, but that's another story.

**Comment by neersighted** [comment]
`/etc/systemd/system` is where the units installed by the local administrator go; I think that's pretty accurate in this scenario, but it's certainly a matter of opinion. That being said, StackOverflow/most users are going to be most familiar with that path, which gives merit to suggesting it by default.

**Comment by afbjorklund** [comment]
As suspected, it is related to selinux.

`setenforce 0` makes it work

https://stopdisablingselinux.com/

`setenforce 1` makes it fail

```
Failed to enable unit: Unit file cri-docker.service does not exist.
Failed to enable unit: Unit file cri-docker.socket does not exist.
```

**Comment by Manojkl** [comment]
> 
manojkl@fedora:[~]: cd /etc/systemd/system/
basic.target.wants/                                      network-online.target.wants/
bluetooth.target.wants/                                  remote-fs.target.wants/
default.target.wants/                                    sockets.target.wants/
dev-virtio\x2dports-org.qemu.guest_agent.0.device.wants/ sysinit.target.wants/
getty.target.wants/                                      timers.target.wants/
graphical.target.wants/                                  user@.service.wants/
local-fs.target.wants/                                   vmtoolsd.service.requires/
multi-user.target.wants/      

These are the files in the folder and not able to find .socket or .services file

**Comment by Manojkl** [comment]
Thanks for the comments. Problem solved with the installation. Tried to install  with `install` rather than `cp -a` and it worked.

**Comment by afbjorklund** [comment]
> These are the files in the folder and not able to find .socket or .services file

"cd" \<tab\> only lists directories, "ls" \<tab\> would list both

**Comment by afbjorklund** [comment]
There is no mention of the packages upstream, they just refer to the developer documentation in the github README.

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

> 1. On each of your nodes, install Docker for your Linux distribution as per [Install Docker Engine](https://docs.docker.com/engine/install/#server).
>
> 2. Install [cri-dockerd](https://github.com/Mirantis/cri-dockerd), following the instructions in that source code repository.

**Comment by afbjorklund** [comment]
Another minor quirk is that the GitHub landing page only considers packages deployed to the GitHub repository:

> [**Releases (8)**](https://github.com/Mirantis/cri-dockerd/releases)
>
> `v0.3.0` (Latest)
> 2 weeks ago
> [+ 7 releases](https://github.com/Mirantis/cri-dockerd/releases)
> 
> [**Packages**](https://github.com/orgs/Mirantis/packages?repo_name=cri-dockerd)
> 
> No packages published

Which _could_ lead the casual reader to think that there are no deb/rpm packages published, and not look any further ?

It would probably need more text, like https://github.com/containerd/containerd/blob/main/docs/getting-started.md

**Comment by neersighted** [comment]
I turned off the packages discovery to hopefully drive people towards the releases page (indeed, GitHub packages does not support Linux distribution packages).
