### ISSUE TITLE
./installer_linux安装失败

### ISSUE THREAD

**Issue by 1llqqhh** [Mirantis/cri-dockerd#166]
[root@controller docker]# ./installer_linux
Welcome to the Go installer!
Getting current Go version failed: Get https://golang.org/VERSION?m=text: dial tcp 172.217.160.113:443: i/o timeout
[root@controller docker]#

**Comment by neersighted** [comment]
This is not related to cri-dockerd; `installer_linux` is merely a tool used to fetch the latest version of Go. Please fetch a working copy of the latest version of Go from a source that is not firewalled, and otherwise continue as documented.
