### ISSUE TITLE
Upgrade to v0.3.2 all pods crashed

### ISSUE THREAD

**Issue by leonanu** [Mirantis/cri-dockerd#172]
OS: Debian 11.6
cri-dockered version: 0.3.2
docker-ce version: 23.0.2-1~debian.11~bullseye
kubernetes version: v1.26.3

After upgraded v0.3.2 all pods failed to start. Rollback to v0.3.1 everything goes well.

**Comment by leonanu** [comment]
"eth0" netns="/proc/207576/ns/net"
Apr 01 14:23:54 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.803 [INFO][208122] k8s.go 583: Releasing IP address(es) ContainerID="fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676"
Apr 01 14:23:54 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.803 [INFO][208122] utils.go 195: Calico CNI releasing IP address ContainerID="fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676"
Apr 01 14:23:54 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.854 [INFO][208174] ipam_plugin.go 416: Releasing address using handleID ContainerID="fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676" HandleID="k8s-pod-network.fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676" Workload="k8s-k8s-metrics--server--6f6cdbf67d--9d8sf-eth0"
Apr 01 14:23:54 k8s cri-dockerd[1327]: time="2023-04-01T14:23:54+08:00" level=info msg="About to acquire host-wide IPAM lock." source="ipam_plugin.go:357"
Apr 01 14:23:54 k8s cri-dockerd[1327]: time="2023-04-01T14:23:54+08:00" level=info msg="Acquired host-wide IPAM lock." source="ipam_plugin.go:372"
Apr 01 14:23:54 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.901 [INFO][208174] ipam_plugin.go 435: Released address using handleID ContainerID="fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676" HandleID="k8s-pod-network.fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676" Workload="k8s-k8s-metrics--server--6f6cdbf67d--9d8sf-eth0"
Apr 01 14:23:54 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.901 [INFO][208174] ipam_plugin.go 444: Releasing address using workloadID ContainerID="fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676" HandleID="k8s-pod-network.fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676" Workload="k8s-k8s-metrics--server--6f6cdbf67d--9d8sf-eth0"
Apr 01 14:23:54 k8s cri-dockerd[1327]: time="2023-04-01T14:23:54+08:00" level=info msg="Released host-wide IPAM lock." source="ipam_plugin.go:378"
Apr 01 14:23:54 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.916 [INFO][208122] k8s.go 589: Teardown processing complete. ContainerID="fccae8c47cc8a73fbe1dfa6724e627db674859ea466e5d047637265faea0d676"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.789 [INFO][208145] k8s.go 576: Cleaning up netns ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.790 [INFO][208145] dataplane_linux.go 524: Deleting workload's device in netns. ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" iface="eth0" netns="/proc/207356/ns/net"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.790 [INFO][208145] dataplane_linux.go 535: Entered netns, deleting veth. ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" iface="eth0" netns="/proc/207356/ns/net"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.827 [INFO][208145] dataplane_linux.go 569: Deleted device in netns. ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" after=37.326303ms iface="eth0" netns="/proc/207356/ns/net"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.827 [INFO][208145] k8s.go 583: Releasing IP address(es) ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.827 [INFO][208145] utils.go 195: Calico CNI releasing IP address ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.933 [INFO][208212] ipam_plugin.go 416: Releasing address using handleID ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" HandleID="k8s-pod-network.da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" Workload="k8s-k8s-openvpn--7f6d97f685--mltks-eth0"
Apr 01 14:23:55 k8s cri-dockerd[1327]: time="2023-04-01T14:23:54+08:00" level=info msg="About to acquire host-wide IPAM lock." source="ipam_plugin.go:357"
Apr 01 14:23:55 k8s cri-dockerd[1327]: time="2023-04-01T14:23:54+08:00" level=info msg="Acquired host-wide IPAM lock." source="ipam_plugin.go:372"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:55.081 [INFO][208212] ipam_plugin.go 435: Released address using handleID ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" HandleID="k8s-pod-network.da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" Workload="k8s-k8s-openvpn--7f6d97f685--mltks-eth0"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:55.081 [INFO][208212] ipam_plugin.go 444: Releasing address using workloadID ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" HandleID="k8s-pod-network.da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d" Workload="k8s-k8s-openvpn--7f6d97f685--mltks-eth0"
Apr 01 14:23:55 k8s cri-dockerd[1327]: time="2023-04-01T14:23:55+08:00" level=info msg="Released host-wide IPAM lock." source="ipam_plugin.go:378"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:55.086 [INFO][208145] k8s.go 589: Teardown processing complete. ContainerID="da14bf236ab0a356048a8c753769c0985dd9560cf8ed43dac59e5003aa59ef3d"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.884 [INFO][208201] k8s.go 576: Cleaning up netns ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.884 [INFO][208201] dataplane_linux.go 524: Deleting workload's device in netns. ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" iface="eth0" netns="/proc/207343/ns/net"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.884 [INFO][208201] dataplane_linux.go 535: Entered netns, deleting veth. ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" iface="eth0" netns="/proc/207343/ns/net"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.915 [INFO][208201] dataplane_linux.go 569: Deleted device in netns. ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" after=30.884486ms iface="eth0" netns="/proc/207343/ns/net"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.915 [INFO][208201] k8s.go 583: Releasing IP address(es) ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:54.915 [INFO][208201] utils.go 195: Calico CNI releasing IP address ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:55.041 [INFO][208278] ipam_plugin.go 416: Releasing address using handleID ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" HandleID="k8s-pod-network.aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" Workload="k8s-k8s-calico--kube--controllers--5857bf8d58--b5tmh-eth0"
Apr 01 14:23:55 k8s cri-dockerd[1327]: time="2023-04-01T14:23:55+08:00" level=info msg="About to acquire host-wide IPAM lock." source="ipam_plugin.go:357"
Apr 01 14:23:55 k8s cri-dockerd[1327]: time="2023-04-01T14:23:55+08:00" level=info msg="Acquired host-wide IPAM lock." source="ipam_plugin.go:372"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:55.126 [INFO][208278] ipam_plugin.go 435: Released address using handleID ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" HandleID="k8s-pod-network.aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" Workload="k8s-k8s-calico--kube--controllers--5857bf8d58--b5tmh-eth0"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:55.126 [INFO][208278] ipam_plugin.go 444: Releasing address using workloadID ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" HandleID="k8s-pod-network.aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d" Workload="k8s-k8s-calico--kube--controllers--5857bf8d58--b5tmh-eth0"
Apr 01 14:23:55 k8s cri-dockerd[1327]: time="2023-04-01T14:23:55+08:00" level=info msg="Released host-wide IPAM lock." source="ipam_plugin.go:378"
Apr 01 14:23:55 k8s cri-dockerd[1327]: 2023-04-01 14:23:55.130 [INFO][208201] k8s.go 589: Teardown processing complete. ContainerID="aeaf236101c058117a9db06b2901e53b5f8d846dff034211ac18a942ccb5547d"

**Comment by leonanu** [comment]
Sorry Bro, due to release reverted. I can't get v0.3.2 again. If could, I'll pleasure to provide full logs about dockerd, cri-dockerd and kubelet etc. Thank you.

**Comment by nwneisen** [comment]
Closing this issue as it was related to a reverted release. If the issue exists in the current release then we c an take a look
