### ISSUE TITLE
Upcoming K8s v1.27 removes util functions being used.

### ISSUE THREAD

**Issue by dereknola** [Mirantis/cri-dockerd#175]
https://github.com/Mirantis/cri-dockerd/blob/master/network/hostport/hostport_manager.go#L70 Is currently using `conntrack.Exists` which was removed in the upcoming K8s v1.27.0 https://github.com/kubernetes/kubernetes/pull/115103. The code will need to be modified to account for this.

**Comment by HirazawaUi** [comment]
I was responsible for removing the unused code in k8s.io/kubernetes/pkg/util, and if allowed i would like fixing the issue in cri-dockerd that has arisen.

**Comment by nwneisen** [comment]
Was this covered in #177 or are there additional changes that will need to be made?

**Comment by neersighted** [comment]
I think we should be good closing this issue out, though the actual work to vendor in K8s 1.27 will still need to be done.

**Comment by dereknola** [comment]
Additionally, `k8s.io/kubernetes/pkg/util/bandwidth` has been deprecated. In the k3s-io fork I ended up with a commit that I can try and upstream this week. See https://github.com/Mirantis/cri-dockerd/commit/de6550a2f066ecf567ea87c2b23dfc354db52508
