### ISSUE TITLE
`--version` and `--buildinfo` output to stderr

### ISSUE THREAD

**Issue by spowelljr** [Mirantis/cri-dockerd#186]
I was trying to use `cri-dockerd --version` in a bash script but kept getting an empty response, I eventually discovered that it was outputting to stderr.

I believe outputting to stdout would make the most most sense and follow the standard. However, I'm aware there could be a potentially breaking change to others that expect the output to be stderr now. Or maybe this was done on purpose.

I'm happy to make a PR to change it to stdout if you deem it the right thing to do.

**Comment by fLaLaMaster** [comment]
Yeah. idk why someone make this, but if you need to work with this in your scripts, simplest way is to redirect stderr to stdout. Like here:
cri-dockerd --version 2>&1
where 2(stderr) redirected to 1(stdout). And then you can simply manipulate with string:
echo "v$(cri-dockerd --version 2>&1 | awk '{print $2}')"
