### ISSUE TITLE
Create a github page for the documentation

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/cri-dockerd#212]
Many projects host a static website for their documentation. This can be done using github pages so that the docs are contained within the project right next to the code. I'm familiar with [Hugo](https://gohugo.io/) and it'd be nice to stick with a Go SSG so less needs to be installed. There is a free theme that looks nice [geekdocs](https://geekdocs.de/usage/getting-started/) but I'm not particular and we may want to customize this anyway.

- [k0s](https://github.com/k0sproject/k0s) uses github pages and we can leverage their project structure to get everything up and running
- The detailed docs should be within the `docs` folder of the project. Certain markdown files may need to be outside the folder so that github can find them in the github UI. Hugo should be setup to know about these
- A makefile command `make docs` should be added to run the docs locally while working on them
- A github action should be setup to publish updates to the docs when a release is made. This may be out of scope of this issue

**Comment by afbjorklund** [comment]
And sometimes it goes back and forth, like on https://containerd.io/docs/getting-started/

> Moved to https://github.com/containerd/containerd/blob/main/docs/getting-started.md

**Comment by 2rs2ts** [comment]
This is satisfied by #215 and @227, right?

**Comment by nwneisen** [comment]
@2rs2ts Correct. Thanks for pointing that out. This can be closed
