### ISSUE TITLE
cri-dockerd sandbox diffing from kubadm sanbox

### ISSUE THREAD

**Issue by Toavina23** [Mirantis/cri-dockerd#230]
I am getting this error message when initializing my kubernetes cluster 
`detected that the sandbox image "registry.k8s.io/pause:3.6" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using "registry.k8s.io/pause:3.9" as the CRI sandbox image`

The initialization is complete and the cluster is operational but I am a bit worried about the risk of ignoring this warning message.

is there a fix to it ? I did not find a way to override the cri-dockerd sandbox version

**Comment by afbjorklund** [comment]
Unfortunately the documentation is a bit confusing, it ended up under "Mirantis" header:

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

> Overriding the sandbox (pause) image
>
> The `cri-dockerd` adapter accepts a command line argument for specifying which container image to use as the Pod infrastructure container (“pause image”). The command line argument to use is `--pod-infra-container-image`.

**Comment by afbjorklund** [comment]
It will be updated to use pause version 3.9 by default:

* #194

**Comment by Toavina23** [comment]
Okay thanks for the informations.
