### ISSUE TITLE
default socket path on Linux/Windows

### ISSUE THREAD

**Issue by neolit123** [Mirantis/cri-dockerd#24]
hello,
i see different values for the socket path in the packaged systemd socket file:
https://github.com/Mirantis/cri-dockerd/blob/master/packaging/systemd/cri-docker.socket#L6
(has `ListenStream=%t/cri-docker.sock`)

and the default value in:
https://github.com/Mirantis/cri-dockerd/blob/542e27dee12db61d6e96d2a83a20359474a5efa2/src/cmd/cri/options/options.go#L44-L47

the flag has `.../cri-dockerd.sock` (notice the trailing `d`). Windows packaging seems to not overload the default `npipe:////./pipe/cri-dockerd`

we have a pending kubeadm PR for k8s 1.24 where we are hardcoding the cri-dockerd "known" endpoints to the same values as in the cri-dockerd options.go above for Linux/Windows:
https://github.com/kubernetes/kubernetes/pull/107317

i'm assuming that the missing `d` is a typo?
are we safe to use `npipe:////./pipe/cri-dockerd` for Windows and `unix:///var/run/cri-dockerd.sock` for Linux in kubeadm defaults?

cc @evol262 @afbjorklund

**Comment by evol262** [comment]
Yep, the missing `d` is a typo. I'l get a patch up for it in a couple minutes. `cri-dockerd.sock` is correct.

Thanks for checking @neolit123 :D

**Comment by neolit123** [comment]
thanks!

**Comment by afbjorklund** [comment]
We already have hardcoded `cri-docker.sock` everywhere, since it was the values in the systemd units.

**Comment by afbjorklund** [comment]
Note that the name of the service no longer matches the name of the socket. If it matters at all.
