### ISSUE TITLE
Need help on github action System has not been booted with systemd as init system (P\ID 1). Can't operate. [LocalTest/Test k8s backend & chart] | Failed to connect to bus: Host is down

### ISSUE THREAD

**Issue by jmikedupont2** [Mirantis/cri-dockerd#255]
https://dask.discourse.group/t/getting-starting-with-act-locallly-with-podman-need-help-system-has-not-been-booted-with-systemd-as-init-system-p-id-1-cant-operate/2251 I wrote a bug report here

**Comment by nwneisen** [comment]
`cri-dockerd` does not support `podman` and it never will. This is a CRI for `dockerd`. You will need to use a CRI for podman or `dockerd` as your runtime.

**Comment by jmikedupont2** [comment]
same error occurs with docker as well, I think it relates to nektos/act
