### ISSUE TITLE
v0.3.4 Assets in v0.3.5 release 

### ISSUE THREAD

**Issue by angudadevops** [Mirantis/cri-dockerd#256]
## Expected Behavior

I can see 0.3.4 assets are in 0.3.5 release

https://github.com/Mirantis/cri-dockerd/releases/tag/v0.3.5

## Actual Behavior

Expected to see 0.3.5 assets

**Comment by nwneisen** [comment]
Thanks for pointing this out. I forgot to pull the tag. I've removed these assets and I'm rebuilding with the correct tag now
