### ISSUE TITLE
Include license file in RPMs

### ISSUE THREAD

**Issue by matthewtorr-msft** [Mirantis/cri-dockerd#266]
## Expected Behavior
RPM should install the LICENSE file to a sensible location such as `/usr/share/licenses/cri-dockerd-<version>/`.

Please consider adding this as it would help simplify license compliance for users.

It could be accomplished by adding `%license LICENSE` to the `%files` section of the spec file.

## Actual Behavior
Only the binary and the systemd files are included.

```
$ rpm -ql cri-dockerd
/usr/bin/cri-dockerd
/usr/lib/systemd/system/cri-docker.service
/usr/lib/systemd/system/cri-docker.socket
```

## Specifications

  - Version: 0.3.4 and above
  - Platform: CentOS 7 / RHEL 8

Assuming RPMs for other platforms and versions are also affected.

**Comment by afbjorklund** [comment]
It does have the package header:

`packaging/rpm/SPECS/cri-dockerd.spec:License: ASL 2.0`

**Comment by afbjorklund** [comment]
@matthewtorr-msft : none of the other Docker packages have any license file included.
