### ISSUE TITLE
Change the documentation to match the systemd unit files

### ISSUE THREAD

**Issue by afbjorklund** [Mirantis/cri-dockerd#27]
~~Need the new "cri-dockerd" name, too. So that it matches the README~~

`systemctl enable --now cri-dockerd.socket`

Since:
* #24

---

Alternatively, the README could be updated to reflect the systemd units ?

That is: keep the "cri-docker" name, and make sure everyone uses that.

`systemctl enable --now cri-docker.socket`

**Comment by tao12345666333** [comment]
Simply renamed #31

**Comment by afbjorklund** [comment]
As the saying goes: "there is no such thing as a simple rename".

**Comment by afbjorklund** [comment]
Probably too late now, that 0.2.0 is starting to be used and documented exernally.
