### ISSUE TITLE
Update Go Versions

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/cri-dockerd#272]
Recent package updates for our packaging tools required me to bump us up to Go 19+. Thankfully, there was still an image available for us and this was a straightforward process. 

I looked at bumping us to an even newer version and turned out to be more involved. Partially because the a buster golang image is no longer available and we will have to switch to bookworm. This is just a ticket to start getting the project updated to more recent versions.

**Comment by afbjorklund** [comment]
The go.mod has already been set to `go1.21`
