### ISSUE TITLE
May I ask which version should be downloaded without Debian12? I don't think Bookworm is available

### ISSUE THREAD

**Issue by zxh451200** [Mirantis/cri-dockerd#276]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by afbjorklund** [comment]
You can download the tarball, unfortunately the deb and the rpm are separated by distribution release and architecture.

**Comment by afbjorklund** [comment]
But it _would_ be nice to have some more deb packages, for debian bookworm and for ubuntu jammy (including arm64)...

**Comment by nwneisen** [comment]
I noticed that we don't have a bookworm version. Adding one was part of my thoughts with https://github.com/Mirantis/cri-dockerd/issues/272

**Comment by afbjorklund** [comment]
There is no difference between them anyway (besides timestamps), so I am not sure why bother?

`Files cri-dockerd_0.3.7.3-0.debian-bullseye_amd64/usr/bin/cri-dockerd and cri-dockerd_0.3.7.3-0.debian-buster_amd64/usr/bin/cri-dockerd are identical`

The main difference between the .tgz and the .deb's, is that it is statically linked (while they are not).

But there could probably be a single .deb package and a single .rpm package, like it is done in pkg.k8s.io?

`Files cri-dockerd-0.3.7.20231027185657.170103f2-0.el7.x86_64/usr/bin/cri-dockerd and cri-dockerd-0.3.7.20231027185657.170103f2-0.el8.x86_64/usr/bin/cri-dockerd are identical`

The only difference between rpm and deb, is that rpm re-strips the binaries and puts in debuginfo.

**Comment by nwneisen** [comment]
@afbjorklund Sounds like a plan to me

**Comment by lixiaoyuner** [comment]
@afbjorklund, will you plan to add bookworm dep file into release list?

**Comment by afbjorklund** [comment]
https://github.com/Mirantis/cri-dockerd/issues/276#issuecomment-1808346398

I don't think it matters, which deb you use.

**Comment by lixiaoyuner** [comment]
> [#276 (comment)](https://github.com/Mirantis/cri-dockerd/issues/276#issuecomment-1808346398)
> 
> I don't think it matters, which deb you use. But hope that they will get added anyway.

Thanks for your response, will the bookworm deb package be in the next release assets? Or it will take much longer time to add?

**Comment by afbjorklund** [comment]
I don't know the release plan, and I think that it was already responded to above
