### ISSUE TITLE
Request for Docker API 1.44 support update

### ISSUE THREAD

**Issue by jstewart612** [Mirantis/cri-dockerd#299]
## Expected Behavior
crictl inspecti calls using cri-dockerd work on Docker Engine 25 (API version 1.44

## Actual Behavior
```
[root@nuc-5 ~]# crictl --runtime-endpoint=unix:///run/k3s/cri-dockerd/cri-dockerd.sock inspecti docker.io/democraticcsi/csi-grpc-proxy:v0.5.3
E0119 19:35:45.041342  131086 remote_image.go:157] "ImageStatus failed" err="Id or size of image \"docker.io/democraticcsi/csi-grpc-proxy:v0.5.3\" is not set" image="docker.io/democraticcsi/csi-grpc-proxy:v0.5.3"
FATA[0000] image status for "docker.io/democraticcsi/csi-grpc-proxy:v0.5.3" request: Id or size of image "docker.io/democraticcsi/csi-grpc-proxy:v0.5.3" is not set
[root@nuc-5 ~]#
```

## Steps to Reproduce the Problem

1. Install Docker Engine 25
2. Have any running cri-dockerd instance against it (k3s 1.29.0 in this case is how I'm running it)
3. Issue the above inspecti command after a pull
4. Watch the error pop out

## Specifications

  - Version: 0.3.9
  - Platform: Almalinux 9
  - Subsystem: Docker Engine 25 with k3s 1.29.0

**Comment by jstewart612** [comment]
Discovered during https://github.com/k3s-io/k3s/issues/9279

**Comment by afbjorklund** [comment]
Apparently the field was deprecated in Docker v1.10, and unused since 1.43.

```go
        // Size is the total size of the image including all layers it is composed of.
        Size int64

        // VirtualSize is the total size of the image including all layers it is
        // composed of.
        //
        // In versions of Docker before v1.10, this field was calculated from
        // the image itself and all of its parent images. Docker v1.10 and up
        // store images self-contained, and no longer use a parent-chain, making
        // this field an equivalent of the Size field.
        //
        // Deprecated: Unused in API 1.43 and up, but kept for backward compatibility with older API versions.
        VirtualSize int64 `json:"VirtualSize,omitempty"`
```

Probably related to all the other image size code being broken for ages as well...

**Comment by afbjorklund** [comment]
Unfortunately Docker (moby) does not seem to be testing their releases with CRI?

And since Kubernetes does not test their releases with Docker, nobody is testing...

**Comment by brandond** [comment]
thanks for the quick fix @afbjorklund !
