### ISSUE TITLE
Need method of providing git commit information

### ISSUE THREAD

**Issue by afbjorklund** [Mirantis/cri-dockerd#30]
When not using `git` to build, but a release tarball

From https://github.com/Mirantis/cri-dockerd/issues/19#issuecomment-1005520300

Optionally also support SOURCE_DATE_EPOCH.

https://reproducible-builds.org/

**Comment by afbjorklund** [comment]
As long as the build doesn't fail, it's OK to leave it empty.

It looks weird, but 70's seems to be "industry standard".

Like podman:
```json
    "GitCommit": "",
    "BuiltTime": "Thu Jan  1 01:00:00 1970",
```

**Comment by afbjorklund** [comment]
So these values are recorded, and provided:
```
REVISION=$(git log -1 --pretty=%H)
SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
```

`eb0c48ef49856f7d098ec005ddebcae197e08e49`
`1641267182`

**Comment by evol262** [comment]
`REVISION`, `SOURCE_DATE_EPOCH`, and `VERSION` can now be set as environment variables or build-time options to `make`. 

There's a `--buildinfo` flag to `cri-dockerd` which will show what they were set to.
