### ISSUE TITLE
`libdocker.GenerateMountBindings()`: Disable RRO mounts when bumping up the Docker API client package to v25 (API v1.44)

### ISSUE THREAD

**Issue by AkihiroSuda** [Mirantis/cri-dockerd#309]
https://github.com/Mirantis/cri-dockerd/blob/8ae7a0ee2a81ec928aee8a276ffe6ba0ec6125ba/libdocker/helpers.go#L205-L261

Docker v25 (API v1.44) treats read-only mounts as recursively read-only by default: https://github.com/moby/moby/pull/45278#issuecomment-1499557245

But this appeared to be too much breaking for Kubernetes: https://github.com/kubernetes/enhancements/pull/3858#issuecomment-1925441072

So cri-dockerd has to disable RRO by setting `BindOptions.ReadOnlyNonRecursive`.

**Comment by AkihiroSuda** [comment]
(This needs migrating from the legacy bind strings to the modern mount structs, but migrating "Z" isn't straightforward)

**Comment by AkihiroSuda** [comment]
PR:
- #311

**Comment by afbjorklund** [comment]
Should probably have been 0.4.0, and not 0.3.12

**Comment by neersighted** [comment]
Hindsight being what it is, probably. At the time this seemed like a pretty simple bugfix for an unintended regression caused by an unintended API change.
