### ISSUE TITLE
To install, on a Linux system that uses systemd, and already has Docker Engine installed

### ISSUE THREAD

**Issue by fadikhan11** [Mirantis/cri-dockerd#323]
This worked for me. otherwise an error occurs:
root@kubemaster1:~/cri-dockerd# install -o root -g root -m 0755 cri-dockerd /usr/local/bin/cri-dockerd
install: cannot stat 'cri-dockerd': No such file or directory

Solution:
$ # Run these commands as root
cd cri-dockerd
mkdir -p /usr/local/bin

wget https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.10/cri-dockerd-0.3.10.amd64.tgz

tar -xvf tar -xvf cri-dockerd-0.3.10.amd64.tgz
cd cri-dockerd/
install -o root -g root -m 0755 cri-dockerd /usr/local/bin/cri-dockerd
cd .. 
install packaging/systemd/* /etc/systemd/system
sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
systemctl daemon-reload
systemctl enable --now cri-docker.socket

**Comment by neersighted** [comment]
You attempted to install cri-dockerd without locally compiling, or downloading a tarball first. Of course this failed; if you see any deficiencies in the README that you believe mislead you to attempt the install steps out of order, please open a PR.

**Comment by fadikhan11** [comment]
first i tried by cloning git as mentioned in README:

git clone https://github.com/Mirantis/cri-dockerd.git

after that i these commands as mentioned in README:
# Run these commands as root
cd cri-dockerd
mkdir -p /usr/local/bin
install -o root -g root -m 0755 cri-dockerd /usr/local/bin/cri-dockerd 
**install: cannot stat 'cri-dockerd': No such file or directory**
so issue starts from here. that y i provided above solution that worked for me.

**Comment by neersighted** [comment]
You missed the `make cri-dockerd` (the 'local compile') mentioned above those steps in the README.

**Comment by fadikhan11** [comment]
but that is for POSIX environment. I am using ubuntu.

**Comment by neersighted** [comment]
POSIX is used here to mean 'Unix-like,' there haven't been any POSIX-certified systems in a very long time. Unfortunately the phrase has aquired this meaning in the absence of any real POSIX.

**Comment by fadikhan11** [comment]
by the way i also tried "make cri-dockerd" in my ubuntu 22 but that wasn't worked. that y i did this at the end and it worked.

**Comment by neersighted** [comment]
Did you have a working Go compiler as per the install instructions? Please provide `go version` output if you can.

**Comment by neersighted** [comment]
Also, as a Ubuntu user you should prefer the pre-build .deb packages from https://github.com/Mirantis/cri-dockerd/releases, which are mentioned in the README section above the 'Advanced Install' (which is what you did).

**Comment by neersighted** [comment]
The .deb packages contain all the files and don't require any steps beyond `dpkg -i <filename>.deb`.

**Comment by fadikhan11** [comment]
ok. i haven't tested .deb package yet. i will try Insha'Allah.
