### ISSUE TITLE
 When deleting a container in exit status, kubelet will have an err log

### ISSUE THREAD

**Issue by mcrrx** [Mirantis/cri-dockerd#342]
`3月 29 14:36:50 k8s-master-01 kubelet[1543]: E0329 14:36:50.433169    1543 cri_stats_provider.go:675] "Unable to fetch container log stats" err="failed to get fsstats for \"/var/log/pods/kube-system_kube-scheduler-k8s-master-01_037a4aa188b45d4fc4b922147ff829c0/kube-scheduler/7.log\": no such file or directory" containerName="kube-scheduler"

3月 29 14:36:59 k8s-master-01 kubelet[1543]: E0329 14:36:59.822659    1543 cri_stats_provider.go:675] "Unable to fetch container log stats" err="failed to get fsstats for \"/var/log/pods/kube-system_kube-scheduler-k8s-master-01_037a4aa188b45d4fc4b922147ff829c0/kube-scheduler/2.log\": no such file or directory" containerName="kube-scheduler"

3月 29 14:36:59 k8s-master-01 kubelet[1543]: E0329 14:36:59.822659    1543 cri_stats_provider.go:675] "Unable to fetch container log stats" err="failed to get fsstats for \"/var/log/pods/kube-system_kube-scheduler-k8s-master-01_037a4aa188b45d4fc4b922147ff829c0/kube-scheduler/4.log\": no such file or directory" containerName="kube-scheduler"
`

以上是kubelet的报错信息

目前这边能确认的问题就是，容器删除时创建的软连接未删除，导致kubelet一直去找，找不到文件
暂时解决办法：删除对应的软连接就好了

请问为何会这样，有没有方法可以做到我删除容器时，创建的日志软链接也会自动删除

**Comment by dpanech-wr** [comment]
I'm having the same issue. @nwneisen care to comment?
