### ISSUE TITLE
Any reason why the 0.3.15 release is not marked as "latest"?

### ISSUE THREAD

**Issue by jandubois** [Mirantis/cri-dockerd#388]
I assume it is just an oversight.

Also any update when we can expect a (pre-)release of 0.4.x (to get #350 into an "official" release, even if just a pre-release)?

**Comment by afbjorklund** [comment]
@nwneisen

**Comment by afbjorklund** [comment]
* https://github.com/Mirantis/cri-dockerd/issues/395

**Comment by nwneisen** [comment]
0.3.15 was not marked as the latest since the 0.3.x branch is now only for legacy support. This is also the branch that Mirantis will continue to use and support.

I left 0.4.x for those wanting to update the libraries and get the latest changes into cri-dockerd

**Comment by afbjorklund** [comment]
I think the original question was why 0.3.14 is the latest, and not 0.3.15

Once 0.4.0 is out, it would probably become the latest (as you mention)
