### ISSUE TITLE
Please make a cri-dockerd release and package

### ISSUE THREAD

**Issue by afbjorklund** [Mirantis/cri-dockerd#4]
Now that Kubernetes 1.23 is in alpha, it would be nice with a `0.1.0` release and some binaries... (like static and deb/rpm)

https://www.mirantis.com/blog/the-future-of-dockershim-is-cri-dockerd/

> There is a Makefile with a few targets. `make deb` or `make rpm` will probably have you covered, and you can install the packages as normal. If you’re using a different distribution, `make static` will give you raw binaries you can invoke.

I expect to be able to download these, from the GibHub release "assets"

**Comment by evol262** [comment]
Will be done MOnday.

**Comment by travisghansen** [comment]
Will these be published to the docker repos for yum and apt as well?

**Comment by evol262** [comment]
They are not likely to be, unless someone from upstream Docker picks them up

**Comment by travisghansen** [comment]
I thought mirantis was upstream docker now. Thanks for the heads up!

**Comment by evol262** [comment]
We work with them, but the upstream community is a community ;)

**Comment by sftim** [comment]
This issue will be relevant to https://github.com/kubernetes/kubernetes/issues/104878
(if `cri-dockerd` gets a public release, then people who want to use Docker as a container runtime for Kubernetes have a route to continue doing that)

**Comment by evol262** [comment]
Releases are published. Anything else needed here?

**Comment by afbjorklund** [comment]
Thanks!
