### ISSUE TITLE
Unable to get logs

### ISSUE THREAD

**Issue by wzshiming** [Mirantis/cri-dockerd#40]
Unable to get logs after using cri-dockerd with Kubelet, everything else looks good.

``` console
crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock  logs f96a85c2686f4
FATA[0000] failed to try resolving symlinks in path "/var/log/pods/kube-system_kube-apiserver-zsm-test-0_cb68ef30a75a5673ba80d69dedf5b217/kube-apiserver/2.log": lstat /var/log/pods/kube-system_kube-apiserver-zsm-test-0_cb68ef30a75a5673ba80d69dedf5b217/kube-apiserver/2.log: no such file or directory
```

``` console
kubectl logs -f -n kube-system           kube-apiserver-zsm-test-0
failed to try resolving symlinks in path "/var/log/pods/kube-system_kube-apiserver-zsm-test-0_cb68ef30a75a5673ba80d69dedf5b217/kube-apiserver/2.log": lstat /var/log/pods/kube-system_kube-apiserver-zsm-test-0_cb68ef30a75a5673ba80d69dedf5b217/kube-apiserver/2.log: no such file or directory
```

**Comment by afbjorklund** [comment]
Works from here, the symlinks are resolving to `/var/lib/docker/containers/` OK.

**Comment by wzshiming** [comment]
I tried it but it still doesn't work
It is found that the docker on the machine is 1.13, which is the default of centos 7
try to upgrade docker then it works.
Thanks.

**Comment by afbjorklund** [comment]
I don't think Docker 1.13 (a.k.a. 17.03) is supported anymore, even on CentOS 7 (from 2014)

**Comment by afbjorklund** [comment]
I think that `cri-dockerd` needs to document and verify requirements on the Docker Engine.

**Comment by wzshiming** [comment]
> I don't think Docker 1.13 (a.k.a. 17.03) is supported anymore, even on CentOS 7 (from 2014)
> 
> https://docs.docker.com/engine/release-notes/17.03/
> 
> https://docs.docker.com/engine/install/centos/

Agreed

> I think that `cri-dockerd` needs to document and verify requirements on the Docker Engine.
> 
> Kubernetes version 1.16 still supported Docker 1.13.1, while version 1.24 doesn't "support" any.
> 
> Kubernetes version	Validated version
> 1.12	17.03
> 1.13	18.06
> 1.14	18.09
> 1.18	19.03
> 1.20	None

I am also very concerned about this matter. I'm writing a migration script for a future upgrade to k8s 1.24. :)

https://github.com/klts-io/setup-cri-dockerd
