### ISSUE TITLE
Is this project still being maintained ?

### ISSUE THREAD

**Issue by afbjorklund** [Mirantis/cri-dockerd#8]
Or should the issues be opened elsewhere instead ?

https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/

> Otherwise, if you’re using the open source Docker Engine, the dockershim project will be available as an open source component, and you will be able to continue to use it with Kubernetes; it will just require a small configuration change, which we will document.

ping @evol262

**Comment by jewertow** [comment]
@Frostman  could you help?

**Comment by evol262** [comment]
Sorry, I missed this last week. Yes, still being maintained. Please open issues if found

**Comment by afbjorklund** [comment]
Thanks, fixing the systemd socket and making a release seemed like the most urgent...

* Issue #7

* Issue #4

Even if Kubernetes 1.23 alpha still ships with the dockershim (just like cri-dockerd does).

**Comment by afbjorklund** [comment]
> Yes, still being maintained

Any updates ?

**Comment by evol262** [comment]
I’ll have patches up this week

**Comment by afbjorklund** [comment]
Any luck ? (KubeCon week...)
