### ISSUE TITLE
Missing configuration which prevents the correct work of cri-docker for bare metal kubernetes clusters

### ISSUE THREAD

**Issue by vgeorgiev90** [Mirantis/cri-dockerd#96]
Hello i am setting up a kubernetes cluster on bare metal instances with the docker CRI, i am using cri-dockerd according to the docs in kubernetes.io. However it seems that your packaging for systemd is the bare minimum and its missing essential configuration for the setup to work out of the box, because of that very weird and strange behavior occurs, basically the kubelet is trying to use the docker network to assign IP addresses to the pods which leads to issues in the network communication between the pods and its very difficult to debug when you dont know from where to start.

Please add this as a minimum config for kubernetes clusters or at least include some description/examples in the docs.

```
ExecStart=/usr/local/bin/cri-dockerd --network-plugin=cni --cni-bin-dir=/opt/cni/bin --cni-cache-dir=/var/lib/cni/cache --cni-conf-dir=/etc/cni/net.d --pod-infra-container-image=k8s.gcr.io/pause:3.7
```

**Comment by afbjorklund** [comment]
Looks like a duplicate, maybe a separate issue for how to update the pause image (from 3.6 to 3.7) ?

* https://github.com/Mirantis/cri-dockerd/issues/93

**Comment by afbjorklund** [comment]
Note that this would also need an entry in /etc/cni

Like if it should be the default, or something ?
